namespace FileScopedFaker.Tests;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

[TestFixture]
public class GeneratorByte_Test
{
    [Test]
    public void CanGenerate_Test()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Generate_Test()
    {
        Assert.Fail("autogenerated");
    }
}