using System.Reflection;
using Faker.Generators;
using System;
using System.Generic.Collections;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Faker.Generators.Tests
{
    [TestFixture]
    public class GeneratorObject_Test
    {
        [Test]
        public void CreateObject_Test(Type type)
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void FillObject_Test(object item)
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetDefaultValue_Test(Type type)
        {
            Assert.Fail("autogenerated");
        }
    }
}