using Faker.Generators;
using System;
using System.Generic.Collections;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Faker.Generators.Tests
{
    [TestFixture]
    public class GeneratorInt_Test
    {
        [Test]
        public void CanGenerate_Test(Type type)
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Generate_Test(Type typeToGenerate, GeneratorContext context)
        {
            Assert.Fail("autogenerated");
        }
    }
}