using Microsoft.CodeAnalysis;
using Faker.Generators;
using AnothorOne;
using Faker2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Faker.Generators.Tests
{
    namespace AnothorOne.Tests
    {
        [TestFixture]
        public class GeneratorByte_Test
        {
            [Test]
            public void CanGenerate_Test()
            {
                Assert.Fail("autogenerated");
            }

            [Test]
            public void Generate_Test()
            {
                Assert.Fail("autogenerated");
            }
        }
    }
}