using Faker.Generators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Faker.Generators.Tests
{
    [TestFixture]
    public class GeneratorBool_Test
    {
        [Test]
        public void CanGenerate_Test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void CanGenerate_1_Test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Generate_Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}