using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks.Dataflow;
using TestGeneratorLib;
using Dataflow;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Dataflow.Tests
{
    [TestFixture]
    public class Pipeline_Test
    {
        [Test]
        public void PerformProcessing_Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}